; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:seeed_xiao_esp32s3]
platform = espressif32@ 6.8.1
;board = esp32s3box
;board = esp32-s3-devkitm-1
board = seeed_xiao_esp32s3
framework = arduino
lib_deps = 
    https://github.com/moononournation/ArduinoFreeFontFile
    https://github.com/moononournation/Arduino_GFX
    tamctec/TAMC_GT911 @ 1.0.2
monitor_speed = 115200
;build_flags =
;    -std=c++17

; upgrade XTensa32 GCC/G++ compiler to 8.2.0
; use bleeding edge arduino-esp32
;platform_packages =
;    toolchain-xtensa32 @ 2.80200.200226
;    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#idf-release/v4.0